export const data = [
  {
    id: "1",
    email: "john.doe@example.com",
    ird_number: "INRD8374X",
    status: "MANUAL_IDV_REQUESTED",
    intended_transaction_count: 25,
    intended_transaction_amount: 3250.75,
    phone_number: "+1-312-555-0178",
    failureReason: "DOCUMENT_EXPIRED",
    manualNotes: "Customer submitted an expired passport",
    isManualOverridden: false,
    overriddenBy: null,
    overriddenTimestamp: null,
    idvs: [
      {
        status: "FAILED",
        first_name: "John",
        middle_name: "Michael",
        last_name: "Doe",
        street_address: "456 Maple Street",
        Suburb: "Downtown",
        City: "Chicago",
        post_code: "60610",
        country_code: "US",
        DocumentType: "PASSPORT",
        failureCode: "EXPIRED_DOC",
        manualNotes: "Submitted passport expired in 2022",
        isManualOverridden: false,
        overriddenBy: null,
      },
    ],
  },
  {
    id: "2",

    email: "sophia.wilson@outlook.com",
    ird_number: "INRD3927K",
    status: "COMPLETED",
    intended_transaction_count: 48,
    intended_transaction_amount: 9284.6,
    phone_number: "+44-7812-555-032",
    failureReason: null,
    manualNotes: "All documents verified successfully",
    isManualOverridden: false,
    overriddenBy: null,
    overriddenTimestamp: null,
    idvs: [
      {
        status: "COMPLETED",
        first_name: "Sophia",
        middle_name: null,
        last_name: "Wilson",
        street_address: "78 High Street",
        Suburb: "Camden",
        City: "London",
        post_code: "NW1 5PT",
        country_code: "GB",
        DocumentType: "NATIONAL_ID",
        failureCode: null,
        manualNotes: "Clear scan provided",
        isManualOverridden: false,
        overriddenBy: null,
      },
    ],
  },
  {
    id: "3",

    email: "liam.patel@gmail.com",
    ird_number: "INRD5219Q",
    status: "FAILED",
    intended_transaction_count: 10,
    intended_transaction_amount: 1475.3,
    phone_number: "+61-400-555-778",
    failureReason: "FACE_MISMATCH",
    manualNotes: "Mismatch detected between uploaded image and ID photo",
    isManualOverridden: true,
    overriddenBy: "Emma Richardson",
    overriddenTimestamp: "2024-02-12T14:18:09Z",
    idvs: [
      {
        status: "FAILED",
        first_name: "Liam",
        middle_name: "Raj",
        last_name: "Patel",
        street_address: "23 Kangaroo Street",
        Suburb: "Sydney",
        City: "Sydney",
        post_code: "2000",
        country_code: "AU",
        DocumentType: "DRIVERS_LICENSE",
        failureCode: "FACE_MISMATCH",
        manualNotes: "Face verification failed",
        isManualOverridden: true,
        overriddenBy: "Emma Richardson",
      },
    ],
  },
];
